### ISSUE TITLE
Unclear soundness of `PosixDmaBuffer`

### ISSUE THREAD

**Issue by matklad** [DataDog/scipio#79]
Hi!

I've been casually browsing source of scipio (I am really excited about TpC in Rust!), and I *think* [`PosixDmaBuffer`](https://github.com/DataDog/scipio/blob/8a5d10dfbc70b0a199384fdca745f13fb8240a55/scipio/src/sys/posix_buffers.rs#L14) might lead to undefined behavior. At least, it's not clear to me why that wouldn't be the case.

Here are my notes:

* `PosixDmaBuffer::trim_to_size` and `PosixDmaBuffer::trim` methods are safe. However, they don't check that sizes are in bounds, and so can be missused to cause UB. Specifically,  `as_ptr` causes UB, if `data.add(self.trim)` fails in-bounds requirements (sic, *just* pointer arithmetic can cause UB), and `as_bytes` additionally causes UB if `self.size` fails in-bounds.
* By itself, this isn't necessary a problem -- if `PosixDmaBuffer` is not a public type, then the crate itself might just be careful enough to use it correctly. It's not obvious from the source if the type is indeed public, but making it `pub(crate)` and fixing re-exports clears this up.
* However, there might be indirect UB exposed still. `PosixDmaBuffer` is used by the `DmaFile`, and I *think* that might lead to UB.
* Specifically, I feel that something like `read_dma(1, usize::MAX)` might be UB. I haven't traced the code thoroughly so I might be wrong, but I think the following would happen:
  * [`b`](https://github.com/DataDog/scipio/blob/8a5d10dfbc70b0a199384fdca745f13fb8240a55/scipio/src/io/dma_file.rs#L401) will be `1`
  * [`eff_size`](https://github.com/DataDog/scipio/blob/8a5d10dfbc70b0a199384fdca745f13fb8240a55/scipio/src/io/dma_file.rs#L403) will be `0` in release due to overflow
  * [`trim_front`](https://github.com/DataDog/scipio/blob/8a5d10dfbc70b0a199384fdca745f13fb8240a55/scipio/src/io/dma_file.rs#L412) will then trim the empty buffer by `1`
* Again, this is just me eyeballing the code, so this particular problem might turn out to be non-problem at all, but it's pretty hard to conclude that no such problems could exist.

My recommendations would be:

* Make `PosixDmaBuffer` `pub(crate)` to be sure it's not accidentally exposed (this also triggers a couple of "unused" warnings -- compiler is better about reasoning about non-`pub` types).
* Make `trim` and `trim_front` methods unsafe and add `debug_assert`s inside, OR add `assert`s.

I'd personally lean towards asserts -- this is IO, so I wouldn't expect bounds checking to be costly.

**Comment by glommer** [comment]
hello hello!!

Thanks for the thorough write up of the issues. Some things to consider:
* `PosixDmaBuffer` **is** a public type. It is exported as `DmaBuffer`, and the idea is that at some point we'll use `io_uring` registered buffers as an option. I just didn't have that time yet to make that work.

However, looking again now in the occasion of your comments, some functions that are currently `pub` should not be. For instance, `new` should not be public: a `DmaBuffer` should never be constructed by the user and just acquired through `DmaFile`. This would give us for example the ability to guarantee that the buffer would always be below a certain size which might be enough for what we're talking about here. `trim` & friends should be `pub(crate)` too because the buffer may be shared through a `ReadResult` and one user should not be allowed to change the underlying buffer boundaries under the other's noses.

However methods allowing access to the buffer contents should be `pub` (maybe only the ones allowing read access to the buffer contents?)

About costs and asserts, keep in mind that I am eyeing Optane-like devices as the prime targets for this. Some of them can read 512 bytes in 4us. So the usual reasoning of "it's I/O, the rest is cheap" doesn't apply here.

*That said*, safety first! I don't want those functions to be behind `unsafe` guarantees and I want them as cheap as possible, but not cheap enough so that to be not usable, marked unsafe, etc.

I will have time to tackle that next week, likely. But wouldn't you like to send us a PR with the above?

Finally thanks again! I am so far having a blast with rust and everyone I have interacted was so nice. Happy to have you around

**Comment by matklad** [comment]
> But wouldn't you like to send us a PR with the above?

No promises here, I am pretty swamped at the moment :)  Though, if I get a chunk of time to read more of scipio, I'll try to make some PRs as well.

**Comment by glommer** [comment]
awesome, no pressure either, it's just awesome to have more people around. If I get to it by next week I'll let you know

**Comment by matklad** [comment]
Submitted #80, and, while doing it, I've noticed a more serious issue:

`copy_from_slice` and `memset` requires only a shared reference (`&self`), which breaks Rust's aliasing guarantees. Specifically, the following code demonstrates unsoundness:

```rust
#[test]
fn unsound() {
    let buf = PosixDmaBuffer::new(4096).unwrap();
    buf.copy_from_slice(0, b"hello");
    let slice = &buf.as_bytes()[..5];
    buf.copy_from_slice(0, b"goodbye");
    assert_eq!(slice, b"hello")
}
```

If my understanding of Rust unsafe semantics is correct, the compiler can assume that `slice` can not be changed by a call to `copy_from_slice` on the next line.

I don't have a quick fix suggestion here -- this one requires understanding of the overall architecture. Like, the obvious fix is suggesting that you "just use `&mut`" here, but you can't as you store buffers behind `Rc`. Some things which might, or might not work:

* use `Rc::get_mut` if you can guarantee at runtime that refcount would be equal to 1 when you fill the buffer
* use `Rc<RefCell<DmaBuffer>>` type to check exclusivness at runtime
* change the contents of `DmaBuffer` from `u8` to `Cell<u8>`. For Cells, mutations via shared references are valid.

**Comment by glommer** [comment]
Thanks a lot! I just saw that you sent two PRs and I will get to them soon.

Is it too obvious already that I spent my last 10 years writing C++? =)

From the options you listed the `Cell` seems to be the best based on my current understanding.
